name: givejobtimer_mobile
description: GiveJobTimer

version: 1.0.6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+3

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  flutter_secure_storage: ^3.3.3
  fluttertoast: ^4.0.0
  flutter_progress_dialog: ^0.1.0
  countup: ^0.1.0
  open_appstore: ^1.0.2
  url_launcher: ^5.4.2
  pin_code_text_field: ^1.7.1
  form_field_validator: ^1.0.1
  dropdown_formfield: ^0.1.2
  flutter_cached_pdfview: ^0.3.1
  slide_popup_dialog: ^0.0.2
  flutter_speed_dial: ^1.2.1
  date_range_picker: ^1.0.6
  date_util: ^0.1.4
  intl: ^0.16.0
  bouncing_widget: ^1.2.0
  shimmer: ^1.1.1
  upgrader: ^2.7.3
  splashscreen: ^1.3.5
  draggable_widget: ^1.0.1
  number_inc_dec: ^0.6.6
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "images/logo.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - lib/internationalization/lang/en.json
    - lib/internationalization/lang/pl.json
    - lib/internationalization/lang/uk.json

    - images/animated-logo.gif

    - images/logo.png
    - images/plumko-logo.png
    - images/givejob-medica-logo.png
    - images/facebook-logo.png
    - images/instagram-logo.png
    - images/linkedin-logo.png
    - images/viber-logo.png
    - images/whatsapp-logo.png

    - images/dark-help-icon.png
    - images/dark-hours-icon.png
    - images/dark-play-icon.png
    - images/dark-stop-icon.png
    - images/big-employee-icon.png
    - images/big-manager-icon.png
    - images/big-employees-icon.png
    - images/big-workplace-icon.png
    - images/big-employee-work-icon.png
    - images/big-contact-with-manager-icon.png
    - images/small-employees-icon.png
    - images/small-workplace-icon.png
    - images/company-icon.png
    - images/group-icon.png
    - images/groups-icon.png
    - images/hours-icon.png
    - images/play-icon.png
    - images/stop-icon.png

    - docs/regulations.pdf
    - docs/privacy_policy.pdf
